#!/bin/bash

export DISPLAY=:8.0

case $1 in
	xfce)
		optirun startxfce4 &
	;;
	openbox)
		optirun openbox-session &
	;;
	kde)
		optirun startkde &
	;;
	*)
		optirun openbox-session &
	;;
esac

sleep 2
synergys -f -a 127.0.0.1 --display :0 -n laptop &
sleep 2
synergyc -f -n hdmi --display :8 127.0.0.1 &

export DISPLAY=:0.0

